branches:
  only:
    - master
    
os:
  - Visual Studio 2015
  
environment:
  VULKAN_VERSION: 3.2
  GLFW_VERSION: rt-1.0.39.0

build_script:
 - ./travis_install.sh https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers.git vulkan $VULKAN_VERSION
 - ./travis_install.sh https://github.com/glfw/glfw.git glfw $GLFW_VERSION
