branches:
  only:
    - master
    
os:
  - Visual Studio 2015
  
environment:
  GLFW_VERSION: 3.2
  VULKAN_VERSION: rt-1.0.39.0

build_script:
 - git clone https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers.git vulkan
 - cd vulkan
 - git checkout %VULKAN_VERSION%
