dist: trusty

sudo: required
language: scala

cache:
 - ~/external

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install xorg-dev libglu1-mesa-dev libxkbcommon-dev libwayland-dev libmirclient-dev libxrandr-dev
 - mkdir ~/external
 - git clone https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers.git ~/external/vulkan
 - git checkout --git-dir=~/external/vulkan $VULKAN_VERSION
 - ~/external/vulkan/update_external_sources.sh
 - ~/external/vulkan/cmake -DBUILD_SHARED_LIBS=ON && ~/external/vulkan/make install
 - git clone https://github.com/glfw/glfw.git
 - cd glfw && git checkout $GLFW_VERSION
 - cmake -DBUILD_SHARED_LIBS=ON && make && sudo make install
 - cd ..

scala:
 - 2.11.8

script:
  - sbt clean
  - sbt native/compile
  - sbt compile test

after_success:
 - bash <(curl -s https://codecov.io/bash)

env:
 global:
  - GLFW_VERSION=3.2
  - VULKAN_VERSION=rt-1.0.39.0
