dist: trusty

sudo: required
language: scala

before_install:
 - git clone https://github.com/glfw/glfw.git
 - cd glfw && git checkout $GLFW_VERSION
 - cmake -DBUILD_SHARED_LIBS=ON && make && sudo make install

scala:
 - 2.11.8

script:
  - sbt clean compile coverage test coverageReport

after_success:
 - bash <(curl -s https://codecov.io/bash)

env:
 global:
  - GLFW_VERSION=3.2
