dist: trusty

sudo: required
language: scala

branches:
  only:
  - master

scala:
 - 2.11.8

addons:
 apt:
  packages:
  - xorg-dev
  - libglu1-mesa-dev
  - libxkbcommon-dev
  - libwayland-dev
  - libmirclient-dev
  - libxrandr-dev

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache

before_install:
 - git clone https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers.git vulkan && cd vulkan && git checkout $VULKAN_VERSION
 - ./update_external_sources.sh
 - cmake -DBUILD_SHARED_LIBS=ON && make && sudo make install
 - cd ..
 - git clone https://github.com/glfw/glfw.git && cd glfw && git checkout $GLFW_VERSION
 - cmake -DBUILD_SHARED_LIBS=ON && make && sudo make install
 - cd ..

script:
  - sbt clean
  - sbt native/compile
  - sbt compile test

after_success:
 - bash <(curl -s https://codecov.io/bash)

env:
 global:
  - GLFW_VERSION=3.2
  - VULKAN_VERSION=rt-1.0.39.0
