dist: trusty

sudo: required
language: scala

branches:
  only:
  - master

scala:
 - 2.11.8

addons:
 apt:
  packages:
  - xorg-dev
  - libglu1-mesa-dev
  - libxkbcommon-dev
  - libwayland-dev
  - libmirclient-dev
  - libxrandr-dev

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.external

before_install:
 - ./travis_install.sh https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers.git vulkan $VULKAN_VERSION
 - ./travis_install.sh https://github.com/glfw/glfw.git glfw $GLFW_VERSION

script:
  - sbt clean
  - sbt native/compile
  - sbt compile test

after_success:
 - bash <(curl -s https://codecov.io/bash)

env:
 global:
  - GLFW_VERSION=3.2
  - VULKAN_VERSION=rt-1.0.39.0
